/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef POTENTDRAW_PRIVATE_H
#define POTENTDRAW_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.2.82"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	2
#define VER_BUILD	82
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"pDraw"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"srchub.org/u/mac"
#define PRODUCT_VERSION	""

#endif /*POTENTDRAW_PRIVATE_H*/
