/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef POTENTDRAW_PRIVATE_H
#define POTENTDRAW_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.1.51"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	51
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"ruthlessphysics.com/potent/"
#define PRODUCT_VERSION	""

#endif /*POTENTDRAW_PRIVATE_H*/
